// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: userops/userops.proto

package userops

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageToken     string                 `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_userops_userops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *Pagination) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_userops_userops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetUserOpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOpRequest) Reset() {
	*x = GetUserOpRequest{}
	mi := &file_userops_userops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOpRequest) ProtoMessage() {}

func (x *GetUserOpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOpRequest.ProtoReflect.Descriptor instead.
func (*GetUserOpRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserOpRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetBundlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundlerRequest) Reset() {
	*x = GetBundlerRequest{}
	mi := &file_userops_userops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundlerRequest) ProtoMessage() {}

func (x *GetBundlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundlerRequest.ProtoReflect.Descriptor instead.
func (*GetBundlerRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{3}
}

func (x *GetBundlerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetPaymasterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymasterRequest) Reset() {
	*x = GetPaymasterRequest{}
	mi := &file_userops_userops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymasterRequest) ProtoMessage() {}

func (x *GetPaymasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymasterRequest.ProtoReflect.Descriptor instead.
func (*GetPaymasterRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymasterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetFactoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFactoryRequest) Reset() {
	*x = GetFactoryRequest{}
	mi := &file_userops_userops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFactoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFactoryRequest) ProtoMessage() {}

func (x *GetFactoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFactoryRequest.ProtoReflect.Descriptor instead.
func (*GetFactoryRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{5}
}

func (x *GetFactoryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factory       *string                `protobuf:"bytes,1,opt,name=factory,proto3,oneof" json:"factory,omitempty"`
	PageSize      *uint32                `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_userops_userops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{6}
}

func (x *ListAccountsRequest) GetFactory() string {
	if x != nil && x.Factory != nil {
		return *x.Factory
	}
	return ""
}

func (x *ListAccountsRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListAccountsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListAccountsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Items          []*Account             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageParams *Pagination            `protobuf:"bytes,2,opt,name=next_page_params,json=nextPageParams,proto3" json:"next_page_params,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_userops_userops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{7}
}

func (x *ListAccountsResponse) GetItems() []*Account {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAccountsResponse) GetNextPageParams() *Pagination {
	if x != nil {
		return x.NextPageParams
	}
	return nil
}

type ListBundlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundler       *string                `protobuf:"bytes,1,opt,name=bundler,proto3,oneof" json:"bundler,omitempty"`
	EntryPoint    *string                `protobuf:"bytes,2,opt,name=entry_point,json=entryPoint,proto3,oneof" json:"entry_point,omitempty"`
	PageSize      *uint32                `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBundlesRequest) Reset() {
	*x = ListBundlesRequest{}
	mi := &file_userops_userops_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBundlesRequest) ProtoMessage() {}

func (x *ListBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBundlesRequest.ProtoReflect.Descriptor instead.
func (*ListBundlesRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{8}
}

func (x *ListBundlesRequest) GetBundler() string {
	if x != nil && x.Bundler != nil {
		return *x.Bundler
	}
	return ""
}

func (x *ListBundlesRequest) GetEntryPoint() string {
	if x != nil && x.EntryPoint != nil {
		return *x.EntryPoint
	}
	return ""
}

func (x *ListBundlesRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListBundlesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListBundlesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Items          []*Bundle              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageParams *Pagination            `protobuf:"bytes,2,opt,name=next_page_params,json=nextPageParams,proto3" json:"next_page_params,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListBundlesResponse) Reset() {
	*x = ListBundlesResponse{}
	mi := &file_userops_userops_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBundlesResponse) ProtoMessage() {}

func (x *ListBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBundlesResponse.ProtoReflect.Descriptor instead.
func (*ListBundlesResponse) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{9}
}

func (x *ListBundlesResponse) GetItems() []*Bundle {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListBundlesResponse) GetNextPageParams() *Pagination {
	if x != nil {
		return x.NextPageParams
	}
	return nil
}

type ListUserOpsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Sender          *string                `protobuf:"bytes,1,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	Bundler         *string                `protobuf:"bytes,2,opt,name=bundler,proto3,oneof" json:"bundler,omitempty"`
	Paymaster       *string                `protobuf:"bytes,3,opt,name=paymaster,proto3,oneof" json:"paymaster,omitempty"`
	Factory         *string                `protobuf:"bytes,4,opt,name=factory,proto3,oneof" json:"factory,omitempty"`
	TransactionHash *string                `protobuf:"bytes,5,opt,name=transaction_hash,json=transactionHash,proto3,oneof" json:"transaction_hash,omitempty"`
	EntryPoint      *string                `protobuf:"bytes,6,opt,name=entry_point,json=entryPoint,proto3,oneof" json:"entry_point,omitempty"`
	BundleIndex     *uint32                `protobuf:"varint,7,opt,name=bundle_index,json=bundleIndex,proto3,oneof" json:"bundle_index,omitempty"`
	BlockNumber     *uint64                `protobuf:"varint,8,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	PageSize        *uint32                `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken       *string                `protobuf:"bytes,10,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListUserOpsRequest) Reset() {
	*x = ListUserOpsRequest{}
	mi := &file_userops_userops_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserOpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOpsRequest) ProtoMessage() {}

func (x *ListUserOpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOpsRequest.ProtoReflect.Descriptor instead.
func (*ListUserOpsRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserOpsRequest) GetSender() string {
	if x != nil && x.Sender != nil {
		return *x.Sender
	}
	return ""
}

func (x *ListUserOpsRequest) GetBundler() string {
	if x != nil && x.Bundler != nil {
		return *x.Bundler
	}
	return ""
}

func (x *ListUserOpsRequest) GetPaymaster() string {
	if x != nil && x.Paymaster != nil {
		return *x.Paymaster
	}
	return ""
}

func (x *ListUserOpsRequest) GetFactory() string {
	if x != nil && x.Factory != nil {
		return *x.Factory
	}
	return ""
}

func (x *ListUserOpsRequest) GetTransactionHash() string {
	if x != nil && x.TransactionHash != nil {
		return *x.TransactionHash
	}
	return ""
}

func (x *ListUserOpsRequest) GetEntryPoint() string {
	if x != nil && x.EntryPoint != nil {
		return *x.EntryPoint
	}
	return ""
}

func (x *ListUserOpsRequest) GetBundleIndex() uint32 {
	if x != nil && x.BundleIndex != nil {
		return *x.BundleIndex
	}
	return 0
}

func (x *ListUserOpsRequest) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

func (x *ListUserOpsRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListUserOpsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListUserOpsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Items          []*ListUserOp          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageParams *Pagination            `protobuf:"bytes,2,opt,name=next_page_params,json=nextPageParams,proto3" json:"next_page_params,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListUserOpsResponse) Reset() {
	*x = ListUserOpsResponse{}
	mi := &file_userops_userops_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserOpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOpsResponse) ProtoMessage() {}

func (x *ListUserOpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOpsResponse.ProtoReflect.Descriptor instead.
func (*ListUserOpsResponse) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{11}
}

func (x *ListUserOpsResponse) GetItems() []*ListUserOp {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUserOpsResponse) GetNextPageParams() *Pagination {
	if x != nil {
		return x.NextPageParams
	}
	return nil
}

type ListBundlersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *uint32                `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBundlersRequest) Reset() {
	*x = ListBundlersRequest{}
	mi := &file_userops_userops_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBundlersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBundlersRequest) ProtoMessage() {}

func (x *ListBundlersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBundlersRequest.ProtoReflect.Descriptor instead.
func (*ListBundlersRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{12}
}

func (x *ListBundlersRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListBundlersRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListBundlersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Items          []*Bundler             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageParams *Pagination            `protobuf:"bytes,2,opt,name=next_page_params,json=nextPageParams,proto3" json:"next_page_params,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListBundlersResponse) Reset() {
	*x = ListBundlersResponse{}
	mi := &file_userops_userops_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBundlersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBundlersResponse) ProtoMessage() {}

func (x *ListBundlersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBundlersResponse.ProtoReflect.Descriptor instead.
func (*ListBundlersResponse) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{13}
}

func (x *ListBundlersResponse) GetItems() []*Bundler {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListBundlersResponse) GetNextPageParams() *Pagination {
	if x != nil {
		return x.NextPageParams
	}
	return nil
}

type ListPaymastersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *uint32                `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymastersRequest) Reset() {
	*x = ListPaymastersRequest{}
	mi := &file_userops_userops_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymastersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymastersRequest) ProtoMessage() {}

func (x *ListPaymastersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymastersRequest.ProtoReflect.Descriptor instead.
func (*ListPaymastersRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{14}
}

func (x *ListPaymastersRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListPaymastersRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListPaymastersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Items          []*Paymaster           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageParams *Pagination            `protobuf:"bytes,2,opt,name=next_page_params,json=nextPageParams,proto3" json:"next_page_params,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPaymastersResponse) Reset() {
	*x = ListPaymastersResponse{}
	mi := &file_userops_userops_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymastersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymastersResponse) ProtoMessage() {}

func (x *ListPaymastersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymastersResponse.ProtoReflect.Descriptor instead.
func (*ListPaymastersResponse) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{15}
}

func (x *ListPaymastersResponse) GetItems() []*Paymaster {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListPaymastersResponse) GetNextPageParams() *Pagination {
	if x != nil {
		return x.NextPageParams
	}
	return nil
}

type ListFactoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      *uint32                `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken     *string                `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFactoriesRequest) Reset() {
	*x = ListFactoriesRequest{}
	mi := &file_userops_userops_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFactoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFactoriesRequest) ProtoMessage() {}

func (x *ListFactoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFactoriesRequest.ProtoReflect.Descriptor instead.
func (*ListFactoriesRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{16}
}

func (x *ListFactoriesRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListFactoriesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListFactoriesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Items          []*Factory             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageParams *Pagination            `protobuf:"bytes,2,opt,name=next_page_params,json=nextPageParams,proto3" json:"next_page_params,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListFactoriesResponse) Reset() {
	*x = ListFactoriesResponse{}
	mi := &file_userops_userops_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFactoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFactoriesResponse) ProtoMessage() {}

func (x *ListFactoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFactoriesResponse.ProtoReflect.Descriptor instead.
func (*ListFactoriesResponse) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{17}
}

func (x *ListFactoriesResponse) GetItems() []*Factory {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFactoriesResponse) GetNextPageParams() *Pagination {
	if x != nil {
		return x.NextPageParams
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_userops_userops_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{18}
}

type IndexerStatus struct {
	state                protoimpl.MessageState   `protogen:"open.v1"`
	FinishedPastIndexing bool                     `protobuf:"varint,1,opt,name=finished_past_indexing,json=finishedPastIndexing,proto3" json:"finished_past_indexing,omitempty"`
	V06                  *EntryPointIndexerStatus `protobuf:"bytes,2,opt,name=v06,proto3" json:"v06,omitempty"`
	V07V08               *EntryPointIndexerStatus `protobuf:"bytes,3,opt,name=v07_v08,json=v07V08,proto3" json:"v07_v08,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IndexerStatus) Reset() {
	*x = IndexerStatus{}
	mi := &file_userops_userops_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexerStatus) ProtoMessage() {}

func (x *IndexerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexerStatus.ProtoReflect.Descriptor instead.
func (*IndexerStatus) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{19}
}

func (x *IndexerStatus) GetFinishedPastIndexing() bool {
	if x != nil {
		return x.FinishedPastIndexing
	}
	return false
}

func (x *IndexerStatus) GetV06() *EntryPointIndexerStatus {
	if x != nil {
		return x.V06
	}
	return nil
}

func (x *IndexerStatus) GetV07V08() *EntryPointIndexerStatus {
	if x != nil {
		return x.V07V08
	}
	return nil
}

type EntryPointIndexerStatus struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Enabled                     bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Live                        bool                   `protobuf:"varint,2,opt,name=live,proto3" json:"live,omitempty"`
	PastDbLogsIndexingFinished  bool                   `protobuf:"varint,3,opt,name=past_db_logs_indexing_finished,json=pastDbLogsIndexingFinished,proto3" json:"past_db_logs_indexing_finished,omitempty"`
	PastRpcLogsIndexingFinished bool                   `protobuf:"varint,4,opt,name=past_rpc_logs_indexing_finished,json=pastRpcLogsIndexingFinished,proto3" json:"past_rpc_logs_indexing_finished,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *EntryPointIndexerStatus) Reset() {
	*x = EntryPointIndexerStatus{}
	mi := &file_userops_userops_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryPointIndexerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryPointIndexerStatus) ProtoMessage() {}

func (x *EntryPointIndexerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryPointIndexerStatus.ProtoReflect.Descriptor instead.
func (*EntryPointIndexerStatus) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{20}
}

func (x *EntryPointIndexerStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EntryPointIndexerStatus) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

func (x *EntryPointIndexerStatus) GetPastDbLogsIndexingFinished() bool {
	if x != nil {
		return x.PastDbLogsIndexingFinished
	}
	return false
}

func (x *EntryPointIndexerStatus) GetPastRpcLogsIndexingFinished() bool {
	if x != nil {
		return x.PastRpcLogsIndexingFinished
	}
	return false
}

type Account struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Address                 string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Factory                 *string                `protobuf:"bytes,2,opt,name=factory,proto3,oneof" json:"factory,omitempty"`
	CreationTransactionHash *string                `protobuf:"bytes,3,opt,name=creation_transaction_hash,json=creationTransactionHash,proto3,oneof" json:"creation_transaction_hash,omitempty"`
	CreationOpHash          *string                `protobuf:"bytes,4,opt,name=creation_op_hash,json=creationOpHash,proto3,oneof" json:"creation_op_hash,omitempty"`
	CreationTimestamp       *string                `protobuf:"bytes,5,opt,name=creation_timestamp,json=creationTimestamp,proto3,oneof" json:"creation_timestamp,omitempty"`
	TotalOps                uint32                 `protobuf:"varint,6,opt,name=total_ops,json=totalOps,proto3" json:"total_ops,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_userops_userops_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{21}
}

func (x *Account) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Account) GetFactory() string {
	if x != nil && x.Factory != nil {
		return *x.Factory
	}
	return ""
}

func (x *Account) GetCreationTransactionHash() string {
	if x != nil && x.CreationTransactionHash != nil {
		return *x.CreationTransactionHash
	}
	return ""
}

func (x *Account) GetCreationOpHash() string {
	if x != nil && x.CreationOpHash != nil {
		return *x.CreationOpHash
	}
	return ""
}

func (x *Account) GetCreationTimestamp() string {
	if x != nil && x.CreationTimestamp != nil {
		return *x.CreationTimestamp
	}
	return ""
}

func (x *Account) GetTotalOps() uint32 {
	if x != nil {
		return x.TotalOps
	}
	return 0
}

type Bundle struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash string                 `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Bundler         string                 `protobuf:"bytes,2,opt,name=bundler,proto3" json:"bundler,omitempty"`
	BlockNumber     uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BundleIndex     uint32                 `protobuf:"varint,4,opt,name=bundle_index,json=bundleIndex,proto3" json:"bundle_index,omitempty"`
	Timestamp       string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalOps        uint32                 `protobuf:"varint,6,opt,name=total_ops,json=totalOps,proto3" json:"total_ops,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_userops_userops_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{22}
}

func (x *Bundle) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *Bundle) GetBundler() string {
	if x != nil {
		return x.Bundler
	}
	return ""
}

func (x *Bundle) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Bundle) GetBundleIndex() uint32 {
	if x != nil {
		return x.BundleIndex
	}
	return 0
}

func (x *Bundle) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Bundle) GetTotalOps() uint32 {
	if x != nil {
		return x.TotalOps
	}
	return 0
}

type Bundler struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TotalBundles  uint32                 `protobuf:"varint,2,opt,name=total_bundles,json=totalBundles,proto3" json:"total_bundles,omitempty"`
	TotalOps      uint32                 `protobuf:"varint,3,opt,name=total_ops,json=totalOps,proto3" json:"total_ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bundler) Reset() {
	*x = Bundler{}
	mi := &file_userops_userops_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundler) ProtoMessage() {}

func (x *Bundler) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundler.ProtoReflect.Descriptor instead.
func (*Bundler) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{23}
}

func (x *Bundler) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Bundler) GetTotalBundles() uint32 {
	if x != nil {
		return x.TotalBundles
	}
	return 0
}

func (x *Bundler) GetTotalOps() uint32 {
	if x != nil {
		return x.TotalOps
	}
	return 0
}

type Paymaster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TotalOps      uint32                 `protobuf:"varint,2,opt,name=total_ops,json=totalOps,proto3" json:"total_ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paymaster) Reset() {
	*x = Paymaster{}
	mi := &file_userops_userops_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paymaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paymaster) ProtoMessage() {}

func (x *Paymaster) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paymaster.ProtoReflect.Descriptor instead.
func (*Paymaster) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{24}
}

func (x *Paymaster) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Paymaster) GetTotalOps() uint32 {
	if x != nil {
		return x.TotalOps
	}
	return 0
}

type Factory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TotalAccounts uint32                 `protobuf:"varint,2,opt,name=total_accounts,json=totalAccounts,proto3" json:"total_accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Factory) Reset() {
	*x = Factory{}
	mi := &file_userops_userops_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Factory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Factory) ProtoMessage() {}

func (x *Factory) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Factory.ProtoReflect.Descriptor instead.
func (*Factory) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{25}
}

func (x *Factory) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Factory) GetTotalAccounts() uint32 {
	if x != nil {
		return x.TotalAccounts
	}
	return 0
}

type UserOp struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Hash                 string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Sender               string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Nonce                string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	CallData             string                 `protobuf:"bytes,4,opt,name=call_data,json=callData,proto3" json:"call_data,omitempty"`
	CallGasLimit         string                 `protobuf:"bytes,5,opt,name=call_gas_limit,json=callGasLimit,proto3" json:"call_gas_limit,omitempty"`
	VerificationGasLimit string                 `protobuf:"bytes,6,opt,name=verification_gas_limit,json=verificationGasLimit,proto3" json:"verification_gas_limit,omitempty"`
	PreVerificationGas   string                 `protobuf:"bytes,7,opt,name=pre_verification_gas,json=preVerificationGas,proto3" json:"pre_verification_gas,omitempty"`
	MaxFeePerGas         string                 `protobuf:"bytes,8,opt,name=max_fee_per_gas,json=maxFeePerGas,proto3" json:"max_fee_per_gas,omitempty"`
	MaxPriorityFeePerGas string                 `protobuf:"bytes,9,opt,name=max_priority_fee_per_gas,json=maxPriorityFeePerGas,proto3" json:"max_priority_fee_per_gas,omitempty"`
	Signature            string                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	Raw                  *structpb.Struct       `protobuf:"bytes,11,opt,name=raw,proto3" json:"raw,omitempty"`
	Aggregator           *string                `protobuf:"bytes,12,opt,name=aggregator,proto3,oneof" json:"aggregator,omitempty"`
	AggregatorSignature  *string                `protobuf:"bytes,13,opt,name=aggregator_signature,json=aggregatorSignature,proto3,oneof" json:"aggregator_signature,omitempty"`
	EntryPoint           string                 `protobuf:"bytes,14,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	EntryPointVersion    string                 `protobuf:"bytes,15,opt,name=entry_point_version,json=entryPointVersion,proto3" json:"entry_point_version,omitempty"`
	TransactionHash      string                 `protobuf:"bytes,16,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	BlockNumber          uint64                 `protobuf:"varint,17,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash            string                 `protobuf:"bytes,18,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Bundler              string                 `protobuf:"bytes,19,opt,name=bundler,proto3" json:"bundler,omitempty"`
	BundleIndex          uint32                 `protobuf:"varint,20,opt,name=bundle_index,json=bundleIndex,proto3" json:"bundle_index,omitempty"`
	Index                uint32                 `protobuf:"varint,21,opt,name=index,proto3" json:"index,omitempty"`
	Factory              *string                `protobuf:"bytes,22,opt,name=factory,proto3,oneof" json:"factory,omitempty"`
	Paymaster            *string                `protobuf:"bytes,23,opt,name=paymaster,proto3,oneof" json:"paymaster,omitempty"`
	Status               bool                   `protobuf:"varint,24,opt,name=status,proto3" json:"status,omitempty"`
	RevertReason         *string                `protobuf:"bytes,25,opt,name=revert_reason,json=revertReason,proto3,oneof" json:"revert_reason,omitempty"`
	Gas                  string                 `protobuf:"bytes,26,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice             string                 `protobuf:"bytes,27,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasUsed              string                 `protobuf:"bytes,28,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	SponsorType          string                 `protobuf:"bytes,29,opt,name=sponsor_type,json=sponsorType,proto3" json:"sponsor_type,omitempty"`
	UserLogsStartIndex   uint32                 `protobuf:"varint,30,opt,name=user_logs_start_index,json=userLogsStartIndex,proto3" json:"user_logs_start_index,omitempty"`
	UserLogsCount        uint32                 `protobuf:"varint,31,opt,name=user_logs_count,json=userLogsCount,proto3" json:"user_logs_count,omitempty"`
	Fee                  string                 `protobuf:"bytes,32,opt,name=fee,proto3" json:"fee,omitempty"`
	Consensus            *bool                  `protobuf:"varint,33,opt,name=consensus,proto3,oneof" json:"consensus,omitempty"`
	Timestamp            *string                `protobuf:"bytes,34,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	ExecuteTarget        *string                `protobuf:"bytes,35,opt,name=execute_target,json=executeTarget,proto3,oneof" json:"execute_target,omitempty"`
	ExecuteCallData      *string                `protobuf:"bytes,36,opt,name=execute_call_data,json=executeCallData,proto3,oneof" json:"execute_call_data,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserOp) Reset() {
	*x = UserOp{}
	mi := &file_userops_userops_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOp) ProtoMessage() {}

func (x *UserOp) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOp.ProtoReflect.Descriptor instead.
func (*UserOp) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{26}
}

func (x *UserOp) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UserOp) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *UserOp) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *UserOp) GetCallData() string {
	if x != nil {
		return x.CallData
	}
	return ""
}

func (x *UserOp) GetCallGasLimit() string {
	if x != nil {
		return x.CallGasLimit
	}
	return ""
}

func (x *UserOp) GetVerificationGasLimit() string {
	if x != nil {
		return x.VerificationGasLimit
	}
	return ""
}

func (x *UserOp) GetPreVerificationGas() string {
	if x != nil {
		return x.PreVerificationGas
	}
	return ""
}

func (x *UserOp) GetMaxFeePerGas() string {
	if x != nil {
		return x.MaxFeePerGas
	}
	return ""
}

func (x *UserOp) GetMaxPriorityFeePerGas() string {
	if x != nil {
		return x.MaxPriorityFeePerGas
	}
	return ""
}

func (x *UserOp) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserOp) GetRaw() *structpb.Struct {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *UserOp) GetAggregator() string {
	if x != nil && x.Aggregator != nil {
		return *x.Aggregator
	}
	return ""
}

func (x *UserOp) GetAggregatorSignature() string {
	if x != nil && x.AggregatorSignature != nil {
		return *x.AggregatorSignature
	}
	return ""
}

func (x *UserOp) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

func (x *UserOp) GetEntryPointVersion() string {
	if x != nil {
		return x.EntryPointVersion
	}
	return ""
}

func (x *UserOp) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *UserOp) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *UserOp) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *UserOp) GetBundler() string {
	if x != nil {
		return x.Bundler
	}
	return ""
}

func (x *UserOp) GetBundleIndex() uint32 {
	if x != nil {
		return x.BundleIndex
	}
	return 0
}

func (x *UserOp) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UserOp) GetFactory() string {
	if x != nil && x.Factory != nil {
		return *x.Factory
	}
	return ""
}

func (x *UserOp) GetPaymaster() string {
	if x != nil && x.Paymaster != nil {
		return *x.Paymaster
	}
	return ""
}

func (x *UserOp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UserOp) GetRevertReason() string {
	if x != nil && x.RevertReason != nil {
		return *x.RevertReason
	}
	return ""
}

func (x *UserOp) GetGas() string {
	if x != nil {
		return x.Gas
	}
	return ""
}

func (x *UserOp) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *UserOp) GetGasUsed() string {
	if x != nil {
		return x.GasUsed
	}
	return ""
}

func (x *UserOp) GetSponsorType() string {
	if x != nil {
		return x.SponsorType
	}
	return ""
}

func (x *UserOp) GetUserLogsStartIndex() uint32 {
	if x != nil {
		return x.UserLogsStartIndex
	}
	return 0
}

func (x *UserOp) GetUserLogsCount() uint32 {
	if x != nil {
		return x.UserLogsCount
	}
	return 0
}

func (x *UserOp) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *UserOp) GetConsensus() bool {
	if x != nil && x.Consensus != nil {
		return *x.Consensus
	}
	return false
}

func (x *UserOp) GetTimestamp() string {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return ""
}

func (x *UserOp) GetExecuteTarget() string {
	if x != nil && x.ExecuteTarget != nil {
		return *x.ExecuteTarget
	}
	return ""
}

func (x *UserOp) GetExecuteCallData() string {
	if x != nil && x.ExecuteCallData != nil {
		return *x.ExecuteCallData
	}
	return ""
}

type ListUserOp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Hash              string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	EntryPoint        string                 `protobuf:"bytes,2,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	EntryPointVersion string                 `protobuf:"bytes,3,opt,name=entry_point_version,json=entryPointVersion,proto3" json:"entry_point_version,omitempty"`
	BlockNumber       uint64                 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TransactionHash   string                 `protobuf:"bytes,5,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Address           string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Timestamp         string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status            bool                   `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Fee               string                 `protobuf:"bytes,9,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListUserOp) Reset() {
	*x = ListUserOp{}
	mi := &file_userops_userops_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOp) ProtoMessage() {}

func (x *ListUserOp) ProtoReflect() protoreflect.Message {
	mi := &file_userops_userops_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOp.ProtoReflect.Descriptor instead.
func (*ListUserOp) Descriptor() ([]byte, []int) {
	return file_userops_userops_proto_rawDescGZIP(), []int{27}
}

func (x *ListUserOp) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ListUserOp) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

func (x *ListUserOp) GetEntryPointVersion() string {
	if x != nil {
		return x.EntryPointVersion
	}
	return ""
}

func (x *ListUserOp) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ListUserOp) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *ListUserOp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ListUserOp) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ListUserOp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ListUserOp) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

var File_userops_userops_proto protoreflect.FileDescriptor

const file_userops_userops_proto_rawDesc = "" +
	"\n" +
	"\x15userops/userops.proto\x12\x0euserOpsIndexer\x1a\x1cgoogle/protobuf/struct.proto\"H\n" +
	"\n" +
	"Pagination\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"-\n" +
	"\x11GetAccountRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"&\n" +
	"\x10GetUserOpRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"-\n" +
	"\x11GetBundlerRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"/\n" +
	"\x13GetPaymasterRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"-\n" +
	"\x11GetFactoryRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xa3\x01\n" +
	"\x13ListAccountsRequest\x12\x1d\n" +
	"\afactory\x18\x01 \x01(\tH\x00R\afactory\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x02R\tpageToken\x88\x01\x01B\n" +
	"\n" +
	"\b_factoryB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x8b\x01\n" +
	"\x14ListAccountsResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.userOpsIndexer.AccountR\x05items\x12D\n" +
	"\x10next_page_params\x18\x02 \x01(\v2\x1a.userOpsIndexer.PaginationR\x0enextPageParams\"\xd8\x01\n" +
	"\x12ListBundlesRequest\x12\x1d\n" +
	"\abundler\x18\x01 \x01(\tH\x00R\abundler\x88\x01\x01\x12$\n" +
	"\ventry_point\x18\x02 \x01(\tH\x01R\n" +
	"entryPoint\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x03 \x01(\rH\x02R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tH\x03R\tpageToken\x88\x01\x01B\n" +
	"\n" +
	"\b_bundlerB\x0e\n" +
	"\f_entry_pointB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x89\x01\n" +
	"\x13ListBundlesResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.userOpsIndexer.BundleR\x05items\x12D\n" +
	"\x10next_page_params\x18\x02 \x01(\v2\x1a.userOpsIndexer.PaginationR\x0enextPageParams\"\x93\x04\n" +
	"\x12ListUserOpsRequest\x12\x1b\n" +
	"\x06sender\x18\x01 \x01(\tH\x00R\x06sender\x88\x01\x01\x12\x1d\n" +
	"\abundler\x18\x02 \x01(\tH\x01R\abundler\x88\x01\x01\x12!\n" +
	"\tpaymaster\x18\x03 \x01(\tH\x02R\tpaymaster\x88\x01\x01\x12\x1d\n" +
	"\afactory\x18\x04 \x01(\tH\x03R\afactory\x88\x01\x01\x12.\n" +
	"\x10transaction_hash\x18\x05 \x01(\tH\x04R\x0ftransactionHash\x88\x01\x01\x12$\n" +
	"\ventry_point\x18\x06 \x01(\tH\x05R\n" +
	"entryPoint\x88\x01\x01\x12&\n" +
	"\fbundle_index\x18\a \x01(\rH\x06R\vbundleIndex\x88\x01\x01\x12&\n" +
	"\fblock_number\x18\b \x01(\x04H\aR\vblockNumber\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\t \x01(\rH\bR\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\n" +
	" \x01(\tH\tR\tpageToken\x88\x01\x01B\t\n" +
	"\a_senderB\n" +
	"\n" +
	"\b_bundlerB\f\n" +
	"\n" +
	"_paymasterB\n" +
	"\n" +
	"\b_factoryB\x13\n" +
	"\x11_transaction_hashB\x0e\n" +
	"\f_entry_pointB\x0f\n" +
	"\r_bundle_indexB\x0f\n" +
	"\r_block_numberB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x8d\x01\n" +
	"\x13ListUserOpsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.userOpsIndexer.ListUserOpR\x05items\x12D\n" +
	"\x10next_page_params\x18\x02 \x01(\v2\x1a.userOpsIndexer.PaginationR\x0enextPageParams\"x\n" +
	"\x13ListBundlersRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\rH\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tH\x01R\tpageToken\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x8b\x01\n" +
	"\x14ListBundlersResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.userOpsIndexer.BundlerR\x05items\x12D\n" +
	"\x10next_page_params\x18\x02 \x01(\v2\x1a.userOpsIndexer.PaginationR\x0enextPageParams\"z\n" +
	"\x15ListPaymastersRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\rH\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tH\x01R\tpageToken\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x8f\x01\n" +
	"\x16ListPaymastersResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.userOpsIndexer.PaymasterR\x05items\x12D\n" +
	"\x10next_page_params\x18\x02 \x01(\v2\x1a.userOpsIndexer.PaginationR\x0enextPageParams\"y\n" +
	"\x14ListFactoriesRequest\x12 \n" +
	"\tpage_size\x18\x01 \x01(\rH\x00R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tH\x01R\tpageToken\x88\x01\x01B\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x8c\x01\n" +
	"\x15ListFactoriesResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.userOpsIndexer.FactoryR\x05items\x12D\n" +
	"\x10next_page_params\x18\x02 \x01(\v2\x1a.userOpsIndexer.PaginationR\x0enextPageParams\"\x12\n" +
	"\x10GetStatusRequest\"\xc2\x01\n" +
	"\rIndexerStatus\x124\n" +
	"\x16finished_past_indexing\x18\x01 \x01(\bR\x14finishedPastIndexing\x129\n" +
	"\x03v06\x18\x02 \x01(\v2'.userOpsIndexer.EntryPointIndexerStatusR\x03v06\x12@\n" +
	"\av07_v08\x18\x03 \x01(\v2'.userOpsIndexer.EntryPointIndexerStatusR\x06v07V08\"\xd1\x01\n" +
	"\x17EntryPointIndexerStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04live\x18\x02 \x01(\bR\x04live\x12B\n" +
	"\x1epast_db_logs_indexing_finished\x18\x03 \x01(\bR\x1apastDbLogsIndexingFinished\x12D\n" +
	"\x1fpast_rpc_logs_indexing_finished\x18\x04 \x01(\bR\x1bpastRpcLogsIndexingFinished\"\xd9\x02\n" +
	"\aAccount\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\afactory\x18\x02 \x01(\tH\x00R\afactory\x88\x01\x01\x12?\n" +
	"\x19creation_transaction_hash\x18\x03 \x01(\tH\x01R\x17creationTransactionHash\x88\x01\x01\x12-\n" +
	"\x10creation_op_hash\x18\x04 \x01(\tH\x02R\x0ecreationOpHash\x88\x01\x01\x122\n" +
	"\x12creation_timestamp\x18\x05 \x01(\tH\x03R\x11creationTimestamp\x88\x01\x01\x12\x1b\n" +
	"\ttotal_ops\x18\x06 \x01(\rR\btotalOpsB\n" +
	"\n" +
	"\b_factoryB\x1c\n" +
	"\x1a_creation_transaction_hashB\x13\n" +
	"\x11_creation_op_hashB\x15\n" +
	"\x13_creation_timestamp\"\xce\x01\n" +
	"\x06Bundle\x12)\n" +
	"\x10transaction_hash\x18\x01 \x01(\tR\x0ftransactionHash\x12\x18\n" +
	"\abundler\x18\x02 \x01(\tR\abundler\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12!\n" +
	"\fbundle_index\x18\x04 \x01(\rR\vbundleIndex\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\ttotal_ops\x18\x06 \x01(\rR\btotalOps\"e\n" +
	"\aBundler\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12#\n" +
	"\rtotal_bundles\x18\x02 \x01(\rR\ftotalBundles\x12\x1b\n" +
	"\ttotal_ops\x18\x03 \x01(\rR\btotalOps\"B\n" +
	"\tPaymaster\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\ttotal_ops\x18\x02 \x01(\rR\btotalOps\"J\n" +
	"\aFactory\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12%\n" +
	"\x0etotal_accounts\x18\x02 \x01(\rR\rtotalAccounts\"\xa5\v\n" +
	"\x06UserOp\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1b\n" +
	"\tcall_data\x18\x04 \x01(\tR\bcallData\x12$\n" +
	"\x0ecall_gas_limit\x18\x05 \x01(\tR\fcallGasLimit\x124\n" +
	"\x16verification_gas_limit\x18\x06 \x01(\tR\x14verificationGasLimit\x120\n" +
	"\x14pre_verification_gas\x18\a \x01(\tR\x12preVerificationGas\x12%\n" +
	"\x0fmax_fee_per_gas\x18\b \x01(\tR\fmaxFeePerGas\x126\n" +
	"\x18max_priority_fee_per_gas\x18\t \x01(\tR\x14maxPriorityFeePerGas\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\tR\tsignature\x12)\n" +
	"\x03raw\x18\v \x01(\v2\x17.google.protobuf.StructR\x03raw\x12#\n" +
	"\n" +
	"aggregator\x18\f \x01(\tH\x00R\n" +
	"aggregator\x88\x01\x01\x126\n" +
	"\x14aggregator_signature\x18\r \x01(\tH\x01R\x13aggregatorSignature\x88\x01\x01\x12\x1f\n" +
	"\ventry_point\x18\x0e \x01(\tR\n" +
	"entryPoint\x12.\n" +
	"\x13entry_point_version\x18\x0f \x01(\tR\x11entryPointVersion\x12)\n" +
	"\x10transaction_hash\x18\x10 \x01(\tR\x0ftransactionHash\x12!\n" +
	"\fblock_number\x18\x11 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x12 \x01(\tR\tblockHash\x12\x18\n" +
	"\abundler\x18\x13 \x01(\tR\abundler\x12!\n" +
	"\fbundle_index\x18\x14 \x01(\rR\vbundleIndex\x12\x14\n" +
	"\x05index\x18\x15 \x01(\rR\x05index\x12\x1d\n" +
	"\afactory\x18\x16 \x01(\tH\x02R\afactory\x88\x01\x01\x12!\n" +
	"\tpaymaster\x18\x17 \x01(\tH\x03R\tpaymaster\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x18 \x01(\bR\x06status\x12(\n" +
	"\rrevert_reason\x18\x19 \x01(\tH\x04R\frevertReason\x88\x01\x01\x12\x10\n" +
	"\x03gas\x18\x1a \x01(\tR\x03gas\x12\x1b\n" +
	"\tgas_price\x18\x1b \x01(\tR\bgasPrice\x12\x19\n" +
	"\bgas_used\x18\x1c \x01(\tR\agasUsed\x12!\n" +
	"\fsponsor_type\x18\x1d \x01(\tR\vsponsorType\x121\n" +
	"\x15user_logs_start_index\x18\x1e \x01(\rR\x12userLogsStartIndex\x12&\n" +
	"\x0fuser_logs_count\x18\x1f \x01(\rR\ruserLogsCount\x12\x10\n" +
	"\x03fee\x18  \x01(\tR\x03fee\x12!\n" +
	"\tconsensus\x18! \x01(\bH\x05R\tconsensus\x88\x01\x01\x12!\n" +
	"\ttimestamp\x18\" \x01(\tH\x06R\ttimestamp\x88\x01\x01\x12*\n" +
	"\x0eexecute_target\x18# \x01(\tH\aR\rexecuteTarget\x88\x01\x01\x12/\n" +
	"\x11execute_call_data\x18$ \x01(\tH\bR\x0fexecuteCallData\x88\x01\x01B\r\n" +
	"\v_aggregatorB\x17\n" +
	"\x15_aggregator_signatureB\n" +
	"\n" +
	"\b_factoryB\f\n" +
	"\n" +
	"_paymasterB\x10\n" +
	"\x0e_revert_reasonB\f\n" +
	"\n" +
	"_consensusB\f\n" +
	"\n" +
	"_timestampB\x11\n" +
	"\x0f_execute_targetB\x14\n" +
	"\x12_execute_call_data\"\xa1\x02\n" +
	"\n" +
	"ListUserOp\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1f\n" +
	"\ventry_point\x18\x02 \x01(\tR\n" +
	"entryPoint\x12.\n" +
	"\x13entry_point_version\x18\x03 \x01(\tR\x11entryPointVersion\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x04R\vblockNumber\x12)\n" +
	"\x10transaction_hash\x18\x05 \x01(\tR\x0ftransactionHash\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06status\x18\b \x01(\bR\x06status\x12\x10\n" +
	"\x03fee\x18\t \x01(\tR\x03fee2\xf8\a\n" +
	"\x0eUserOpsService\x12H\n" +
	"\n" +
	"GetAccount\x12!.userOpsIndexer.GetAccountRequest\x1a\x17.userOpsIndexer.Account\x12E\n" +
	"\tGetUserOp\x12 .userOpsIndexer.GetUserOpRequest\x1a\x16.userOpsIndexer.UserOp\x12H\n" +
	"\n" +
	"GetBundler\x12!.userOpsIndexer.GetBundlerRequest\x1a\x17.userOpsIndexer.Bundler\x12N\n" +
	"\fGetPaymaster\x12#.userOpsIndexer.GetPaymasterRequest\x1a\x19.userOpsIndexer.Paymaster\x12H\n" +
	"\n" +
	"GetFactory\x12!.userOpsIndexer.GetFactoryRequest\x1a\x17.userOpsIndexer.Factory\x12Y\n" +
	"\fListAccounts\x12#.userOpsIndexer.ListAccountsRequest\x1a$.userOpsIndexer.ListAccountsResponse\x12V\n" +
	"\vListBundles\x12\".userOpsIndexer.ListBundlesRequest\x1a#.userOpsIndexer.ListBundlesResponse\x12V\n" +
	"\vListUserOps\x12\".userOpsIndexer.ListUserOpsRequest\x1a#.userOpsIndexer.ListUserOpsResponse\x12Y\n" +
	"\fListBundlers\x12#.userOpsIndexer.ListBundlersRequest\x1a$.userOpsIndexer.ListBundlersResponse\x12_\n" +
	"\x0eListPaymasters\x12%.userOpsIndexer.ListPaymastersRequest\x1a&.userOpsIndexer.ListPaymastersResponse\x12\\\n" +
	"\rListFactories\x12$.userOpsIndexer.ListFactoriesRequest\x1a%.userOpsIndexer.ListFactoriesResponse\x12L\n" +
	"\tGetStatus\x12 .userOpsIndexer.GetStatusRequest\x1a\x1d.userOpsIndexer.IndexerStatusB3Z1github.com/timefactoryio/block/zero/proto/useropsb\x06proto3"

var (
	file_userops_userops_proto_rawDescOnce sync.Once
	file_userops_userops_proto_rawDescData []byte
)

func file_userops_userops_proto_rawDescGZIP() []byte {
	file_userops_userops_proto_rawDescOnce.Do(func() {
		file_userops_userops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userops_userops_proto_rawDesc), len(file_userops_userops_proto_rawDesc)))
	})
	return file_userops_userops_proto_rawDescData
}

var file_userops_userops_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_userops_userops_proto_goTypes = []any{
	(*Pagination)(nil),              // 0: userOpsIndexer.Pagination
	(*GetAccountRequest)(nil),       // 1: userOpsIndexer.GetAccountRequest
	(*GetUserOpRequest)(nil),        // 2: userOpsIndexer.GetUserOpRequest
	(*GetBundlerRequest)(nil),       // 3: userOpsIndexer.GetBundlerRequest
	(*GetPaymasterRequest)(nil),     // 4: userOpsIndexer.GetPaymasterRequest
	(*GetFactoryRequest)(nil),       // 5: userOpsIndexer.GetFactoryRequest
	(*ListAccountsRequest)(nil),     // 6: userOpsIndexer.ListAccountsRequest
	(*ListAccountsResponse)(nil),    // 7: userOpsIndexer.ListAccountsResponse
	(*ListBundlesRequest)(nil),      // 8: userOpsIndexer.ListBundlesRequest
	(*ListBundlesResponse)(nil),     // 9: userOpsIndexer.ListBundlesResponse
	(*ListUserOpsRequest)(nil),      // 10: userOpsIndexer.ListUserOpsRequest
	(*ListUserOpsResponse)(nil),     // 11: userOpsIndexer.ListUserOpsResponse
	(*ListBundlersRequest)(nil),     // 12: userOpsIndexer.ListBundlersRequest
	(*ListBundlersResponse)(nil),    // 13: userOpsIndexer.ListBundlersResponse
	(*ListPaymastersRequest)(nil),   // 14: userOpsIndexer.ListPaymastersRequest
	(*ListPaymastersResponse)(nil),  // 15: userOpsIndexer.ListPaymastersResponse
	(*ListFactoriesRequest)(nil),    // 16: userOpsIndexer.ListFactoriesRequest
	(*ListFactoriesResponse)(nil),   // 17: userOpsIndexer.ListFactoriesResponse
	(*GetStatusRequest)(nil),        // 18: userOpsIndexer.GetStatusRequest
	(*IndexerStatus)(nil),           // 19: userOpsIndexer.IndexerStatus
	(*EntryPointIndexerStatus)(nil), // 20: userOpsIndexer.EntryPointIndexerStatus
	(*Account)(nil),                 // 21: userOpsIndexer.Account
	(*Bundle)(nil),                  // 22: userOpsIndexer.Bundle
	(*Bundler)(nil),                 // 23: userOpsIndexer.Bundler
	(*Paymaster)(nil),               // 24: userOpsIndexer.Paymaster
	(*Factory)(nil),                 // 25: userOpsIndexer.Factory
	(*UserOp)(nil),                  // 26: userOpsIndexer.UserOp
	(*ListUserOp)(nil),              // 27: userOpsIndexer.ListUserOp
	(*structpb.Struct)(nil),         // 28: google.protobuf.Struct
}
var file_userops_userops_proto_depIdxs = []int32{
	21, // 0: userOpsIndexer.ListAccountsResponse.items:type_name -> userOpsIndexer.Account
	0,  // 1: userOpsIndexer.ListAccountsResponse.next_page_params:type_name -> userOpsIndexer.Pagination
	22, // 2: userOpsIndexer.ListBundlesResponse.items:type_name -> userOpsIndexer.Bundle
	0,  // 3: userOpsIndexer.ListBundlesResponse.next_page_params:type_name -> userOpsIndexer.Pagination
	27, // 4: userOpsIndexer.ListUserOpsResponse.items:type_name -> userOpsIndexer.ListUserOp
	0,  // 5: userOpsIndexer.ListUserOpsResponse.next_page_params:type_name -> userOpsIndexer.Pagination
	23, // 6: userOpsIndexer.ListBundlersResponse.items:type_name -> userOpsIndexer.Bundler
	0,  // 7: userOpsIndexer.ListBundlersResponse.next_page_params:type_name -> userOpsIndexer.Pagination
	24, // 8: userOpsIndexer.ListPaymastersResponse.items:type_name -> userOpsIndexer.Paymaster
	0,  // 9: userOpsIndexer.ListPaymastersResponse.next_page_params:type_name -> userOpsIndexer.Pagination
	25, // 10: userOpsIndexer.ListFactoriesResponse.items:type_name -> userOpsIndexer.Factory
	0,  // 11: userOpsIndexer.ListFactoriesResponse.next_page_params:type_name -> userOpsIndexer.Pagination
	20, // 12: userOpsIndexer.IndexerStatus.v06:type_name -> userOpsIndexer.EntryPointIndexerStatus
	20, // 13: userOpsIndexer.IndexerStatus.v07_v08:type_name -> userOpsIndexer.EntryPointIndexerStatus
	28, // 14: userOpsIndexer.UserOp.raw:type_name -> google.protobuf.Struct
	1,  // 15: userOpsIndexer.UserOpsService.GetAccount:input_type -> userOpsIndexer.GetAccountRequest
	2,  // 16: userOpsIndexer.UserOpsService.GetUserOp:input_type -> userOpsIndexer.GetUserOpRequest
	3,  // 17: userOpsIndexer.UserOpsService.GetBundler:input_type -> userOpsIndexer.GetBundlerRequest
	4,  // 18: userOpsIndexer.UserOpsService.GetPaymaster:input_type -> userOpsIndexer.GetPaymasterRequest
	5,  // 19: userOpsIndexer.UserOpsService.GetFactory:input_type -> userOpsIndexer.GetFactoryRequest
	6,  // 20: userOpsIndexer.UserOpsService.ListAccounts:input_type -> userOpsIndexer.ListAccountsRequest
	8,  // 21: userOpsIndexer.UserOpsService.ListBundles:input_type -> userOpsIndexer.ListBundlesRequest
	10, // 22: userOpsIndexer.UserOpsService.ListUserOps:input_type -> userOpsIndexer.ListUserOpsRequest
	12, // 23: userOpsIndexer.UserOpsService.ListBundlers:input_type -> userOpsIndexer.ListBundlersRequest
	14, // 24: userOpsIndexer.UserOpsService.ListPaymasters:input_type -> userOpsIndexer.ListPaymastersRequest
	16, // 25: userOpsIndexer.UserOpsService.ListFactories:input_type -> userOpsIndexer.ListFactoriesRequest
	18, // 26: userOpsIndexer.UserOpsService.GetStatus:input_type -> userOpsIndexer.GetStatusRequest
	21, // 27: userOpsIndexer.UserOpsService.GetAccount:output_type -> userOpsIndexer.Account
	26, // 28: userOpsIndexer.UserOpsService.GetUserOp:output_type -> userOpsIndexer.UserOp
	23, // 29: userOpsIndexer.UserOpsService.GetBundler:output_type -> userOpsIndexer.Bundler
	24, // 30: userOpsIndexer.UserOpsService.GetPaymaster:output_type -> userOpsIndexer.Paymaster
	25, // 31: userOpsIndexer.UserOpsService.GetFactory:output_type -> userOpsIndexer.Factory
	7,  // 32: userOpsIndexer.UserOpsService.ListAccounts:output_type -> userOpsIndexer.ListAccountsResponse
	9,  // 33: userOpsIndexer.UserOpsService.ListBundles:output_type -> userOpsIndexer.ListBundlesResponse
	11, // 34: userOpsIndexer.UserOpsService.ListUserOps:output_type -> userOpsIndexer.ListUserOpsResponse
	13, // 35: userOpsIndexer.UserOpsService.ListBundlers:output_type -> userOpsIndexer.ListBundlersResponse
	15, // 36: userOpsIndexer.UserOpsService.ListPaymasters:output_type -> userOpsIndexer.ListPaymastersResponse
	17, // 37: userOpsIndexer.UserOpsService.ListFactories:output_type -> userOpsIndexer.ListFactoriesResponse
	19, // 38: userOpsIndexer.UserOpsService.GetStatus:output_type -> userOpsIndexer.IndexerStatus
	27, // [27:39] is the sub-list for method output_type
	15, // [15:27] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_userops_userops_proto_init() }
func file_userops_userops_proto_init() {
	if File_userops_userops_proto != nil {
		return
	}
	file_userops_userops_proto_msgTypes[6].OneofWrappers = []any{}
	file_userops_userops_proto_msgTypes[8].OneofWrappers = []any{}
	file_userops_userops_proto_msgTypes[10].OneofWrappers = []any{}
	file_userops_userops_proto_msgTypes[12].OneofWrappers = []any{}
	file_userops_userops_proto_msgTypes[14].OneofWrappers = []any{}
	file_userops_userops_proto_msgTypes[16].OneofWrappers = []any{}
	file_userops_userops_proto_msgTypes[21].OneofWrappers = []any{}
	file_userops_userops_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userops_userops_proto_rawDesc), len(file_userops_userops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userops_userops_proto_goTypes,
		DependencyIndexes: file_userops_userops_proto_depIdxs,
		MessageInfos:      file_userops_userops_proto_msgTypes,
	}.Build()
	File_userops_userops_proto = out.File
	file_userops_userops_proto_goTypes = nil
	file_userops_userops_proto_depIdxs = nil
}
