// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: userops/userops.proto

package userops

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserOpsService_GetAccount_FullMethodName     = "/userOpsIndexer.UserOpsService/GetAccount"
	UserOpsService_GetUserOp_FullMethodName      = "/userOpsIndexer.UserOpsService/GetUserOp"
	UserOpsService_GetBundler_FullMethodName     = "/userOpsIndexer.UserOpsService/GetBundler"
	UserOpsService_GetPaymaster_FullMethodName   = "/userOpsIndexer.UserOpsService/GetPaymaster"
	UserOpsService_GetFactory_FullMethodName     = "/userOpsIndexer.UserOpsService/GetFactory"
	UserOpsService_ListAccounts_FullMethodName   = "/userOpsIndexer.UserOpsService/ListAccounts"
	UserOpsService_ListBundles_FullMethodName    = "/userOpsIndexer.UserOpsService/ListBundles"
	UserOpsService_ListUserOps_FullMethodName    = "/userOpsIndexer.UserOpsService/ListUserOps"
	UserOpsService_ListBundlers_FullMethodName   = "/userOpsIndexer.UserOpsService/ListBundlers"
	UserOpsService_ListPaymasters_FullMethodName = "/userOpsIndexer.UserOpsService/ListPaymasters"
	UserOpsService_ListFactories_FullMethodName  = "/userOpsIndexer.UserOpsService/ListFactories"
	UserOpsService_GetStatus_FullMethodName      = "/userOpsIndexer.UserOpsService/GetStatus"
)

// UserOpsServiceClient is the client API for UserOpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserOpsServiceClient interface {
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	GetUserOp(ctx context.Context, in *GetUserOpRequest, opts ...grpc.CallOption) (*UserOp, error)
	GetBundler(ctx context.Context, in *GetBundlerRequest, opts ...grpc.CallOption) (*Bundler, error)
	GetPaymaster(ctx context.Context, in *GetPaymasterRequest, opts ...grpc.CallOption) (*Paymaster, error)
	GetFactory(ctx context.Context, in *GetFactoryRequest, opts ...grpc.CallOption) (*Factory, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	ListBundles(ctx context.Context, in *ListBundlesRequest, opts ...grpc.CallOption) (*ListBundlesResponse, error)
	ListUserOps(ctx context.Context, in *ListUserOpsRequest, opts ...grpc.CallOption) (*ListUserOpsResponse, error)
	ListBundlers(ctx context.Context, in *ListBundlersRequest, opts ...grpc.CallOption) (*ListBundlersResponse, error)
	ListPaymasters(ctx context.Context, in *ListPaymastersRequest, opts ...grpc.CallOption) (*ListPaymastersResponse, error)
	ListFactories(ctx context.Context, in *ListFactoriesRequest, opts ...grpc.CallOption) (*ListFactoriesResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*IndexerStatus, error)
}

type userOpsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserOpsServiceClient(cc grpc.ClientConnInterface) UserOpsServiceClient {
	return &userOpsServiceClient{cc}
}

func (c *userOpsServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, UserOpsService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) GetUserOp(ctx context.Context, in *GetUserOpRequest, opts ...grpc.CallOption) (*UserOp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserOp)
	err := c.cc.Invoke(ctx, UserOpsService_GetUserOp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) GetBundler(ctx context.Context, in *GetBundlerRequest, opts ...grpc.CallOption) (*Bundler, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bundler)
	err := c.cc.Invoke(ctx, UserOpsService_GetBundler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) GetPaymaster(ctx context.Context, in *GetPaymasterRequest, opts ...grpc.CallOption) (*Paymaster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Paymaster)
	err := c.cc.Invoke(ctx, UserOpsService_GetPaymaster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) GetFactory(ctx context.Context, in *GetFactoryRequest, opts ...grpc.CallOption) (*Factory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Factory)
	err := c.cc.Invoke(ctx, UserOpsService_GetFactory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, UserOpsService_ListAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) ListBundles(ctx context.Context, in *ListBundlesRequest, opts ...grpc.CallOption) (*ListBundlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBundlesResponse)
	err := c.cc.Invoke(ctx, UserOpsService_ListBundles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) ListUserOps(ctx context.Context, in *ListUserOpsRequest, opts ...grpc.CallOption) (*ListUserOpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserOpsResponse)
	err := c.cc.Invoke(ctx, UserOpsService_ListUserOps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) ListBundlers(ctx context.Context, in *ListBundlersRequest, opts ...grpc.CallOption) (*ListBundlersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBundlersResponse)
	err := c.cc.Invoke(ctx, UserOpsService_ListBundlers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) ListPaymasters(ctx context.Context, in *ListPaymastersRequest, opts ...grpc.CallOption) (*ListPaymastersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymastersResponse)
	err := c.cc.Invoke(ctx, UserOpsService_ListPaymasters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) ListFactories(ctx context.Context, in *ListFactoriesRequest, opts ...grpc.CallOption) (*ListFactoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFactoriesResponse)
	err := c.cc.Invoke(ctx, UserOpsService_ListFactories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOpsServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*IndexerStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexerStatus)
	err := c.cc.Invoke(ctx, UserOpsService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserOpsServiceServer is the server API for UserOpsService service.
// All implementations must embed UnimplementedUserOpsServiceServer
// for forward compatibility.
type UserOpsServiceServer interface {
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	GetUserOp(context.Context, *GetUserOpRequest) (*UserOp, error)
	GetBundler(context.Context, *GetBundlerRequest) (*Bundler, error)
	GetPaymaster(context.Context, *GetPaymasterRequest) (*Paymaster, error)
	GetFactory(context.Context, *GetFactoryRequest) (*Factory, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	ListBundles(context.Context, *ListBundlesRequest) (*ListBundlesResponse, error)
	ListUserOps(context.Context, *ListUserOpsRequest) (*ListUserOpsResponse, error)
	ListBundlers(context.Context, *ListBundlersRequest) (*ListBundlersResponse, error)
	ListPaymasters(context.Context, *ListPaymastersRequest) (*ListPaymastersResponse, error)
	ListFactories(context.Context, *ListFactoriesRequest) (*ListFactoriesResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*IndexerStatus, error)
	mustEmbedUnimplementedUserOpsServiceServer()
}

// UnimplementedUserOpsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserOpsServiceServer struct{}

func (UnimplementedUserOpsServiceServer) GetAccount(context.Context, *GetAccountRequest) (*Account, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedUserOpsServiceServer) GetUserOp(context.Context, *GetUserOpRequest) (*UserOp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserOp not implemented")
}
func (UnimplementedUserOpsServiceServer) GetBundler(context.Context, *GetBundlerRequest) (*Bundler, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBundler not implemented")
}
func (UnimplementedUserOpsServiceServer) GetPaymaster(context.Context, *GetPaymasterRequest) (*Paymaster, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymaster not implemented")
}
func (UnimplementedUserOpsServiceServer) GetFactory(context.Context, *GetFactoryRequest) (*Factory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFactory not implemented")
}
func (UnimplementedUserOpsServiceServer) ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccounts not implemented")
}
func (UnimplementedUserOpsServiceServer) ListBundles(context.Context, *ListBundlesRequest) (*ListBundlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBundles not implemented")
}
func (UnimplementedUserOpsServiceServer) ListUserOps(context.Context, *ListUserOpsRequest) (*ListUserOpsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserOps not implemented")
}
func (UnimplementedUserOpsServiceServer) ListBundlers(context.Context, *ListBundlersRequest) (*ListBundlersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBundlers not implemented")
}
func (UnimplementedUserOpsServiceServer) ListPaymasters(context.Context, *ListPaymastersRequest) (*ListPaymastersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPaymasters not implemented")
}
func (UnimplementedUserOpsServiceServer) ListFactories(context.Context, *ListFactoriesRequest) (*ListFactoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFactories not implemented")
}
func (UnimplementedUserOpsServiceServer) GetStatus(context.Context, *GetStatusRequest) (*IndexerStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedUserOpsServiceServer) mustEmbedUnimplementedUserOpsServiceServer() {}
func (UnimplementedUserOpsServiceServer) testEmbeddedByValue()                        {}

// UnsafeUserOpsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserOpsServiceServer will
// result in compilation errors.
type UnsafeUserOpsServiceServer interface {
	mustEmbedUnimplementedUserOpsServiceServer()
}

func RegisterUserOpsServiceServer(s grpc.ServiceRegistrar, srv UserOpsServiceServer) {
	// If the following call panics, it indicates UnimplementedUserOpsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserOpsService_ServiceDesc, srv)
}

func _UserOpsService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_GetUserOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).GetUserOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_GetUserOp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).GetUserOp(ctx, req.(*GetUserOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_GetBundler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBundlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).GetBundler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_GetBundler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).GetBundler(ctx, req.(*GetBundlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_GetPaymaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymasterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).GetPaymaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_GetPaymaster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).GetPaymaster(ctx, req.(*GetPaymasterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_GetFactory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFactoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).GetFactory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_GetFactory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).GetFactory(ctx, req.(*GetFactoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_ListAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_ListBundles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBundlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).ListBundles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_ListBundles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).ListBundles(ctx, req.(*ListBundlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_ListUserOps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserOpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).ListUserOps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_ListUserOps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).ListUserOps(ctx, req.(*ListUserOpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_ListBundlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBundlersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).ListBundlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_ListBundlers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).ListBundlers(ctx, req.(*ListBundlersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_ListPaymasters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymastersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).ListPaymasters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_ListPaymasters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).ListPaymasters(ctx, req.(*ListPaymastersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_ListFactories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFactoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).ListFactories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_ListFactories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).ListFactories(ctx, req.(*ListFactoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOpsService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOpsServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOpsService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOpsServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserOpsService_ServiceDesc is the grpc.ServiceDesc for UserOpsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserOpsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userOpsIndexer.UserOpsService",
	HandlerType: (*UserOpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _UserOpsService_GetAccount_Handler,
		},
		{
			MethodName: "GetUserOp",
			Handler:    _UserOpsService_GetUserOp_Handler,
		},
		{
			MethodName: "GetBundler",
			Handler:    _UserOpsService_GetBundler_Handler,
		},
		{
			MethodName: "GetPaymaster",
			Handler:    _UserOpsService_GetPaymaster_Handler,
		},
		{
			MethodName: "GetFactory",
			Handler:    _UserOpsService_GetFactory_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _UserOpsService_ListAccounts_Handler,
		},
		{
			MethodName: "ListBundles",
			Handler:    _UserOpsService_ListBundles_Handler,
		},
		{
			MethodName: "ListUserOps",
			Handler:    _UserOpsService_ListUserOps_Handler,
		},
		{
			MethodName: "ListBundlers",
			Handler:    _UserOpsService_ListBundlers_Handler,
		},
		{
			MethodName: "ListPaymasters",
			Handler:    _UserOpsService_ListPaymasters_Handler,
		},
		{
			MethodName: "ListFactories",
			Handler:    _UserOpsService_ListFactories_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _UserOpsService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userops/userops.proto",
}
