// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: zero/proto/sigprovider/sigprovider.proto

package sigprovider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignatureService_CreateSignatures_FullMethodName = "/blockscout.sig_provider.v1.SignatureService/CreateSignatures"
)

// SignatureServiceClient is the client API for SignatureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignatureServiceClient interface {
	CreateSignatures(ctx context.Context, in *CreateSignaturesRequest, opts ...grpc.CallOption) (*CreateSignaturesResponse, error)
}

type signatureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignatureServiceClient(cc grpc.ClientConnInterface) SignatureServiceClient {
	return &signatureServiceClient{cc}
}

func (c *signatureServiceClient) CreateSignatures(ctx context.Context, in *CreateSignaturesRequest, opts ...grpc.CallOption) (*CreateSignaturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSignaturesResponse)
	err := c.cc.Invoke(ctx, SignatureService_CreateSignatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignatureServiceServer is the server API for SignatureService service.
// All implementations must embed UnimplementedSignatureServiceServer
// for forward compatibility.
type SignatureServiceServer interface {
	CreateSignatures(context.Context, *CreateSignaturesRequest) (*CreateSignaturesResponse, error)
	mustEmbedUnimplementedSignatureServiceServer()
}

// UnimplementedSignatureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignatureServiceServer struct{}

func (UnimplementedSignatureServiceServer) CreateSignatures(context.Context, *CreateSignaturesRequest) (*CreateSignaturesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSignatures not implemented")
}
func (UnimplementedSignatureServiceServer) mustEmbedUnimplementedSignatureServiceServer() {}
func (UnimplementedSignatureServiceServer) testEmbeddedByValue()                          {}

// UnsafeSignatureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignatureServiceServer will
// result in compilation errors.
type UnsafeSignatureServiceServer interface {
	mustEmbedUnimplementedSignatureServiceServer()
}

func RegisterSignatureServiceServer(s grpc.ServiceRegistrar, srv SignatureServiceServer) {
	// If the following call panics, it indicates UnimplementedSignatureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignatureService_ServiceDesc, srv)
}

func _SignatureService_CreateSignatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSignaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignatureServiceServer).CreateSignatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignatureService_CreateSignatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignatureServiceServer).CreateSignatures(ctx, req.(*CreateSignaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignatureService_ServiceDesc is the grpc.ServiceDesc for SignatureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignatureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockscout.sig_provider.v1.SignatureService",
	HandlerType: (*SignatureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSignatures",
			Handler:    _SignatureService_CreateSignatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zero/proto/sigprovider/sigprovider.proto",
}

const (
	AbiService_GetFunctionAbi_FullMethodName    = "/blockscout.sig_provider.v1.AbiService/GetFunctionAbi"
	AbiService_GetEventAbi_FullMethodName       = "/blockscout.sig_provider.v1.AbiService/GetEventAbi"
	AbiService_BatchGetEventAbis_FullMethodName = "/blockscout.sig_provider.v1.AbiService/BatchGetEventAbis"
)

// AbiServiceClient is the client API for AbiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AbiServiceClient interface {
	GetFunctionAbi(ctx context.Context, in *GetFunctionAbiRequest, opts ...grpc.CallOption) (*GetFunctionAbiResponse, error)
	GetEventAbi(ctx context.Context, in *GetEventAbiRequest, opts ...grpc.CallOption) (*GetEventAbiResponse, error)
	BatchGetEventAbis(ctx context.Context, in *BatchGetEventAbisRequest, opts ...grpc.CallOption) (*BatchGetEventAbisResponse, error)
}

type abiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAbiServiceClient(cc grpc.ClientConnInterface) AbiServiceClient {
	return &abiServiceClient{cc}
}

func (c *abiServiceClient) GetFunctionAbi(ctx context.Context, in *GetFunctionAbiRequest, opts ...grpc.CallOption) (*GetFunctionAbiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFunctionAbiResponse)
	err := c.cc.Invoke(ctx, AbiService_GetFunctionAbi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *abiServiceClient) GetEventAbi(ctx context.Context, in *GetEventAbiRequest, opts ...grpc.CallOption) (*GetEventAbiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventAbiResponse)
	err := c.cc.Invoke(ctx, AbiService_GetEventAbi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *abiServiceClient) BatchGetEventAbis(ctx context.Context, in *BatchGetEventAbisRequest, opts ...grpc.CallOption) (*BatchGetEventAbisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetEventAbisResponse)
	err := c.cc.Invoke(ctx, AbiService_BatchGetEventAbis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AbiServiceServer is the server API for AbiService service.
// All implementations must embed UnimplementedAbiServiceServer
// for forward compatibility.
type AbiServiceServer interface {
	GetFunctionAbi(context.Context, *GetFunctionAbiRequest) (*GetFunctionAbiResponse, error)
	GetEventAbi(context.Context, *GetEventAbiRequest) (*GetEventAbiResponse, error)
	BatchGetEventAbis(context.Context, *BatchGetEventAbisRequest) (*BatchGetEventAbisResponse, error)
	mustEmbedUnimplementedAbiServiceServer()
}

// UnimplementedAbiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAbiServiceServer struct{}

func (UnimplementedAbiServiceServer) GetFunctionAbi(context.Context, *GetFunctionAbiRequest) (*GetFunctionAbiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFunctionAbi not implemented")
}
func (UnimplementedAbiServiceServer) GetEventAbi(context.Context, *GetEventAbiRequest) (*GetEventAbiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventAbi not implemented")
}
func (UnimplementedAbiServiceServer) BatchGetEventAbis(context.Context, *BatchGetEventAbisRequest) (*BatchGetEventAbisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetEventAbis not implemented")
}
func (UnimplementedAbiServiceServer) mustEmbedUnimplementedAbiServiceServer() {}
func (UnimplementedAbiServiceServer) testEmbeddedByValue()                    {}

// UnsafeAbiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AbiServiceServer will
// result in compilation errors.
type UnsafeAbiServiceServer interface {
	mustEmbedUnimplementedAbiServiceServer()
}

func RegisterAbiServiceServer(s grpc.ServiceRegistrar, srv AbiServiceServer) {
	// If the following call panics, it indicates UnimplementedAbiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AbiService_ServiceDesc, srv)
}

func _AbiService_GetFunctionAbi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFunctionAbiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbiServiceServer).GetFunctionAbi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbiService_GetFunctionAbi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbiServiceServer).GetFunctionAbi(ctx, req.(*GetFunctionAbiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AbiService_GetEventAbi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventAbiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbiServiceServer).GetEventAbi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbiService_GetEventAbi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbiServiceServer).GetEventAbi(ctx, req.(*GetEventAbiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AbiService_BatchGetEventAbis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetEventAbisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbiServiceServer).BatchGetEventAbis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AbiService_BatchGetEventAbis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbiServiceServer).BatchGetEventAbis(ctx, req.(*BatchGetEventAbisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AbiService_ServiceDesc is the grpc.ServiceDesc for AbiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AbiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockscout.sig_provider.v1.AbiService",
	HandlerType: (*AbiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFunctionAbi",
			Handler:    _AbiService_GetFunctionAbi_Handler,
		},
		{
			MethodName: "GetEventAbi",
			Handler:    _AbiService_GetEventAbi_Handler,
		},
		{
			MethodName: "BatchGetEventAbis",
			Handler:    _AbiService_BatchGetEventAbis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zero/proto/sigprovider/sigprovider.proto",
}
