// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: zero/proto/sigprovider/sigprovider.proto

package sigprovider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSignaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abi           string                 `protobuf:"bytes,1,opt,name=abi,proto3" json:"abi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSignaturesRequest) Reset() {
	*x = CreateSignaturesRequest{}
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSignaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSignaturesRequest) ProtoMessage() {}

func (x *CreateSignaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSignaturesRequest.ProtoReflect.Descriptor instead.
func (*CreateSignaturesRequest) Descriptor() ([]byte, []int) {
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSignaturesRequest) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

type CreateSignaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSignaturesResponse) Reset() {
	*x = CreateSignaturesResponse{}
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSignaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSignaturesResponse) ProtoMessage() {}

func (x *CreateSignaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSignaturesResponse.ProtoReflect.Descriptor instead.
func (*CreateSignaturesResponse) Descriptor() ([]byte, []int) {
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP(), []int{1}
}

type Argument struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type       string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Components []*Argument            `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	// this is present only in events
	Indexed *bool `protobuf:"varint,4,opt,name=indexed,proto3,oneof" json:"indexed,omitempty"`
	// decoded value
	Value         string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument) Reset() {
	*x = Argument{}
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument) ProtoMessage() {}

func (x *Argument) ProtoReflect() protoreflect.Message {
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument.ProtoReflect.Descriptor instead.
func (*Argument) Descriptor() ([]byte, []int) {
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP(), []int{2}
}

func (x *Argument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Argument) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Argument) GetComponents() []*Argument {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Argument) GetIndexed() bool {
	if x != nil && x.Indexed != nil {
		return *x.Indexed
	}
	return false
}

func (x *Argument) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Abi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inputs        []*Argument            `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Abi) Reset() {
	*x = Abi{}
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Abi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Abi) ProtoMessage() {}

func (x *Abi) ProtoReflect() protoreflect.Message {
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Abi.ProtoReflect.Descriptor instead.
func (*Abi) Descriptor() ([]byte, []int) {
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP(), []int{3}
}

func (x *Abi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Abi) GetInputs() []*Argument {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type GetFunctionAbiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxInput       string                 `protobuf:"bytes,1,opt,name=tx_input,json=txInput,proto3" json:"tx_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionAbiRequest) Reset() {
	*x = GetFunctionAbiRequest{}
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionAbiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionAbiRequest) ProtoMessage() {}

func (x *GetFunctionAbiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionAbiRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionAbiRequest) Descriptor() ([]byte, []int) {
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP(), []int{4}
}

func (x *GetFunctionAbiRequest) GetTxInput() string {
	if x != nil {
		return x.TxInput
	}
	return ""
}

type GetFunctionAbiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abi           []*Abi                 `protobuf:"bytes,1,rep,name=abi,proto3" json:"abi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionAbiResponse) Reset() {
	*x = GetFunctionAbiResponse{}
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionAbiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionAbiResponse) ProtoMessage() {}

func (x *GetFunctionAbiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionAbiResponse.ProtoReflect.Descriptor instead.
func (*GetFunctionAbiResponse) Descriptor() ([]byte, []int) {
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP(), []int{5}
}

func (x *GetFunctionAbiResponse) GetAbi() []*Abi {
	if x != nil {
		return x.Abi
	}
	return nil
}

type GetEventAbiRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// comma separated hex values, ex. `0x0000..1234,0x0000...5678`
	Topics        string `protobuf:"bytes,2,opt,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventAbiRequest) Reset() {
	*x = GetEventAbiRequest{}
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventAbiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventAbiRequest) ProtoMessage() {}

func (x *GetEventAbiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventAbiRequest.ProtoReflect.Descriptor instead.
func (*GetEventAbiRequest) Descriptor() ([]byte, []int) {
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventAbiRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GetEventAbiRequest) GetTopics() string {
	if x != nil {
		return x.Topics
	}
	return ""
}

type GetEventAbiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abi           []*Abi                 `protobuf:"bytes,1,rep,name=abi,proto3" json:"abi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventAbiResponse) Reset() {
	*x = GetEventAbiResponse{}
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventAbiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventAbiResponse) ProtoMessage() {}

func (x *GetEventAbiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventAbiResponse.ProtoReflect.Descriptor instead.
func (*GetEventAbiResponse) Descriptor() ([]byte, []int) {
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventAbiResponse) GetAbi() []*Abi {
	if x != nil {
		return x.Abi
	}
	return nil
}

type BatchGetEventAbisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*GetEventAbiRequest  `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetEventAbisRequest) Reset() {
	*x = BatchGetEventAbisRequest{}
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetEventAbisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetEventAbisRequest) ProtoMessage() {}

func (x *BatchGetEventAbisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetEventAbisRequest.ProtoReflect.Descriptor instead.
func (*BatchGetEventAbisRequest) Descriptor() ([]byte, []int) {
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetEventAbisRequest) GetRequests() []*GetEventAbiRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchGetEventAbisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*GetEventAbiResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetEventAbisResponse) Reset() {
	*x = BatchGetEventAbisResponse{}
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetEventAbisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetEventAbisResponse) ProtoMessage() {}

func (x *BatchGetEventAbisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zero_proto_sigprovider_sigprovider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetEventAbisResponse.ProtoReflect.Descriptor instead.
func (*BatchGetEventAbisResponse) Descriptor() ([]byte, []int) {
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP(), []int{9}
}

func (x *BatchGetEventAbisResponse) GetResponses() []*GetEventAbiResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_zero_proto_sigprovider_sigprovider_proto protoreflect.FileDescriptor

const file_zero_proto_sigprovider_sigprovider_proto_rawDesc = "" +
	"\n" +
	"(zero/proto/sigprovider/sigprovider.proto\x12\x1ablockscout.sig_provider.v1\"+\n" +
	"\x17CreateSignaturesRequest\x12\x10\n" +
	"\x03abi\x18\x01 \x01(\tR\x03abi\"\x1a\n" +
	"\x18CreateSignaturesResponse\"\xb9\x01\n" +
	"\bArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12D\n" +
	"\n" +
	"components\x18\x03 \x03(\v2$.blockscout.sig_provider.v1.ArgumentR\n" +
	"components\x12\x1d\n" +
	"\aindexed\x18\x04 \x01(\bH\x00R\aindexed\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05valueB\n" +
	"\n" +
	"\b_indexed\"W\n" +
	"\x03Abi\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x06inputs\x18\x02 \x03(\v2$.blockscout.sig_provider.v1.ArgumentR\x06inputs\"2\n" +
	"\x15GetFunctionAbiRequest\x12\x19\n" +
	"\btx_input\x18\x01 \x01(\tR\atxInput\"K\n" +
	"\x16GetFunctionAbiResponse\x121\n" +
	"\x03abi\x18\x01 \x03(\v2\x1f.blockscout.sig_provider.v1.AbiR\x03abi\"@\n" +
	"\x12GetEventAbiRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x16\n" +
	"\x06topics\x18\x02 \x01(\tR\x06topics\"H\n" +
	"\x13GetEventAbiResponse\x121\n" +
	"\x03abi\x18\x01 \x03(\v2\x1f.blockscout.sig_provider.v1.AbiR\x03abi\"f\n" +
	"\x18BatchGetEventAbisRequest\x12J\n" +
	"\brequests\x18\x01 \x03(\v2..blockscout.sig_provider.v1.GetEventAbiRequestR\brequests\"j\n" +
	"\x19BatchGetEventAbisResponse\x12M\n" +
	"\tresponses\x18\x01 \x03(\v2/.blockscout.sig_provider.v1.GetEventAbiResponseR\tresponses2\x93\x01\n" +
	"\x10SignatureService\x12\x7f\n" +
	"\x10CreateSignatures\x123.blockscout.sig_provider.v1.CreateSignaturesRequest\x1a4.blockscout.sig_provider.v1.CreateSignaturesResponse\"\x002\xfe\x02\n" +
	"\n" +
	"AbiService\x12y\n" +
	"\x0eGetFunctionAbi\x121.blockscout.sig_provider.v1.GetFunctionAbiRequest\x1a2.blockscout.sig_provider.v1.GetFunctionAbiResponse\"\x00\x12p\n" +
	"\vGetEventAbi\x12..blockscout.sig_provider.v1.GetEventAbiRequest\x1a/.blockscout.sig_provider.v1.GetEventAbiResponse\"\x00\x12\x82\x01\n" +
	"\x11BatchGetEventAbis\x124.blockscout.sig_provider.v1.BatchGetEventAbisRequest\x1a5.blockscout.sig_provider.v1.BatchGetEventAbisResponse\"\x00B7Z5github.com/timefactoryio/block/zero/proto/sigproviderb\x06proto3"

var (
	file_zero_proto_sigprovider_sigprovider_proto_rawDescOnce sync.Once
	file_zero_proto_sigprovider_sigprovider_proto_rawDescData []byte
)

func file_zero_proto_sigprovider_sigprovider_proto_rawDescGZIP() []byte {
	file_zero_proto_sigprovider_sigprovider_proto_rawDescOnce.Do(func() {
		file_zero_proto_sigprovider_sigprovider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zero_proto_sigprovider_sigprovider_proto_rawDesc), len(file_zero_proto_sigprovider_sigprovider_proto_rawDesc)))
	})
	return file_zero_proto_sigprovider_sigprovider_proto_rawDescData
}

var file_zero_proto_sigprovider_sigprovider_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_zero_proto_sigprovider_sigprovider_proto_goTypes = []any{
	(*CreateSignaturesRequest)(nil),   // 0: blockscout.sig_provider.v1.CreateSignaturesRequest
	(*CreateSignaturesResponse)(nil),  // 1: blockscout.sig_provider.v1.CreateSignaturesResponse
	(*Argument)(nil),                  // 2: blockscout.sig_provider.v1.Argument
	(*Abi)(nil),                       // 3: blockscout.sig_provider.v1.Abi
	(*GetFunctionAbiRequest)(nil),     // 4: blockscout.sig_provider.v1.GetFunctionAbiRequest
	(*GetFunctionAbiResponse)(nil),    // 5: blockscout.sig_provider.v1.GetFunctionAbiResponse
	(*GetEventAbiRequest)(nil),        // 6: blockscout.sig_provider.v1.GetEventAbiRequest
	(*GetEventAbiResponse)(nil),       // 7: blockscout.sig_provider.v1.GetEventAbiResponse
	(*BatchGetEventAbisRequest)(nil),  // 8: blockscout.sig_provider.v1.BatchGetEventAbisRequest
	(*BatchGetEventAbisResponse)(nil), // 9: blockscout.sig_provider.v1.BatchGetEventAbisResponse
}
var file_zero_proto_sigprovider_sigprovider_proto_depIdxs = []int32{
	2,  // 0: blockscout.sig_provider.v1.Argument.components:type_name -> blockscout.sig_provider.v1.Argument
	2,  // 1: blockscout.sig_provider.v1.Abi.inputs:type_name -> blockscout.sig_provider.v1.Argument
	3,  // 2: blockscout.sig_provider.v1.GetFunctionAbiResponse.abi:type_name -> blockscout.sig_provider.v1.Abi
	3,  // 3: blockscout.sig_provider.v1.GetEventAbiResponse.abi:type_name -> blockscout.sig_provider.v1.Abi
	6,  // 4: blockscout.sig_provider.v1.BatchGetEventAbisRequest.requests:type_name -> blockscout.sig_provider.v1.GetEventAbiRequest
	7,  // 5: blockscout.sig_provider.v1.BatchGetEventAbisResponse.responses:type_name -> blockscout.sig_provider.v1.GetEventAbiResponse
	0,  // 6: blockscout.sig_provider.v1.SignatureService.CreateSignatures:input_type -> blockscout.sig_provider.v1.CreateSignaturesRequest
	4,  // 7: blockscout.sig_provider.v1.AbiService.GetFunctionAbi:input_type -> blockscout.sig_provider.v1.GetFunctionAbiRequest
	6,  // 8: blockscout.sig_provider.v1.AbiService.GetEventAbi:input_type -> blockscout.sig_provider.v1.GetEventAbiRequest
	8,  // 9: blockscout.sig_provider.v1.AbiService.BatchGetEventAbis:input_type -> blockscout.sig_provider.v1.BatchGetEventAbisRequest
	1,  // 10: blockscout.sig_provider.v1.SignatureService.CreateSignatures:output_type -> blockscout.sig_provider.v1.CreateSignaturesResponse
	5,  // 11: blockscout.sig_provider.v1.AbiService.GetFunctionAbi:output_type -> blockscout.sig_provider.v1.GetFunctionAbiResponse
	7,  // 12: blockscout.sig_provider.v1.AbiService.GetEventAbi:output_type -> blockscout.sig_provider.v1.GetEventAbiResponse
	9,  // 13: blockscout.sig_provider.v1.AbiService.BatchGetEventAbis:output_type -> blockscout.sig_provider.v1.BatchGetEventAbisResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_zero_proto_sigprovider_sigprovider_proto_init() }
func file_zero_proto_sigprovider_sigprovider_proto_init() {
	if File_zero_proto_sigprovider_sigprovider_proto != nil {
		return
	}
	file_zero_proto_sigprovider_sigprovider_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zero_proto_sigprovider_sigprovider_proto_rawDesc), len(file_zero_proto_sigprovider_sigprovider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_zero_proto_sigprovider_sigprovider_proto_goTypes,
		DependencyIndexes: file_zero_proto_sigprovider_sigprovider_proto_depIdxs,
		MessageInfos:      file_zero_proto_sigprovider_sigprovider_proto_msgTypes,
	}.Build()
	File_zero_proto_sigprovider_sigprovider_proto = out.File
	file_zero_proto_sigprovider_sigprovider_proto_goTypes = nil
	file_zero_proto_sigprovider_sigprovider_proto_depIdxs = nil
}
